name: Docker Build & Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库
      - name: Checkout repo
        uses: actions/checkout@v3

      #  设置 Docker 登录
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 拉取 Eridanus 源码
      - name: Clone Eridanus
        run: |
          git clone --depth=1 https://github.com/AOrbitron/Eridanus.git /tmp/eridanus


      #  构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build \
            --build-arg REQUIREMENTS_FILE=/tmp/eridanus/requirements.txt \
            -t zhende1113/eridanus-docker-unofficial:latest .

      # 推送到 Docker Hub
      - name: Push Docker image
        run: |
          docker push zhende1113/eridanus-docker-unofficial:latest
