name: Docker Build & Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出 Antlia 仓库
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. 设置 Docker 登录
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. 构建并推送 Docker 镜像
      - name: Build and Push Docker image
        run: |
          docker build -t zhende1113/eridanus-docker-unofficial:latest .
          docker push zhende1113/eridanus-docker-unofficial:latest